---
title: "About"
description: Active
date: 2023-01-11
---

# Open Source Developer Relations Handbook template

This is a handbook for sets of people who work in Open Source Developer Relations. It's meant to be a set of guidelines and information that a team can use on how they work, that they can use as their own reference and to share with other stakeholders.

These handbooks are meant to be living documents, meant to evolve and change. Documentation is only useful if it's referenced and used, so you want to continue to adapt structure and content in a way that works for it to be most helpful to you. 

These are some ideas and resources on how open source developer relations can work, and templates and guidelines that could be useful to people in similar roles. 


### Acknowledgements

This handbook template was developed by Mara Averick, Mine Cetinkaya-Rundel, Greg Swinehart, Tracy Teal, Andy Teucher, and Charlotte Wickham. It is adapted from the Quarto Team Handbook developed by Al Manning.  






